---
- name: compute setup after undercloud install
  hosts: computes 
  remote_user: heat-admin
  become: true
  vars_files:
    - vars/compute.yml
  tasks:
    - include: tasks/repo.yml
    - name: install wget
      yum:
        name: wget
        state: present
    - name: create rpm package directory
      file:
        path: "{{install_dir}}"
        state: directory
        mode: 0755
    - include: tasks/tuned.yml
    - name: update ovs and modifies config
      script: scripts/update_ovs.sh
    - name: reboot the node
      shell: "nohup sh -c '( sleep 5 ; shutdown -r now )' &" 
      async: 0
      poll: 0
      ignore_errors: true
    - name: wait for reboot complete 
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
      sudo: false
    - name: update ovs DB
      script: scripts/update_ovs_db.sh
    - name: copy pmd core mapping script
      copy: src=scripts/pmdinfo.sh dest=/root/pmdinfo.sh owner=root group=root mode=0777
