---
- name: get kernel mac1
  shell: |
    echo $(ip link show dev eth1 | sed -n -r 's/.*ether ([a-f0-9:]+).*/\1/p')
  register: mac1
  when: routing != "vpp"
- name: VM kernel mac2
  shell: |
    echo $(ip link show dev eth2 | sed -n -r 's/.*ether ([a-f0-9:]+).*/\1/p')
  register: mac2
  when: routing != "vpp"
- name: get vpp mac1
  shell: |
    mac=$(vppctl show hardware-interfaces | grep -A 1 "GigabitEthernet0/4/0" | awk '/address/ {print $3}')
    echo $mac
  register: mac1
  when: routing == "vpp"
- name: get vpp mac2
  shell: |
    mac=$(vppctl show hardware-interfaces | grep -A 1 "GigabitEthernet0/5/0" | awk '/address/ {print $3}')
    echo $mac
  register: mac2
  when: routing == "vpp"

