#!/bin/bash
modprobe uio_pci_generic
dpdk-devbind --unbind 00:04.0 
dpdk-devbind --bind=uio_pci_generic 00:04.0
./testpmd -l 0,1 --socket-mem 1024 -n 4 --proc-type auto --file-prefix pg -w 000:04.0 -- --nb-cores=1 --nb-ports=1 --portmask=1 --port-topology=chained --forward-mode=macswap --interactive --auto-start --rxq=1 --txq=1 --rxd=256 --txd=256

